name: Test and Deploy Hugo site

on:
  push:
    branches:
      - main
      - draft
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  ARTEFACT_NAME: hugo-site
  HUGO_PUBLISHDIR: ./public

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.1
      HUGO_CACHEDIR: /tmp/hugo_cache
      HUGO_RESOURCEDIR: /tmp/hugo_resources
    steps:
      - name: Install Hugo CLI
        run: |
          wget -nv -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      # Thanks https://github.com/peaceiris/actions-hugo
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.HUGO_CACHEDIR }}
            ${{ env.HUGO_RESOURCEDIR }}
          key: ${{ runner.os }}-hugo-cache-main-${{ steps.extract_branch.outputs.branch }}
          restore-keys: |
              ${{ runner.os }}-hugo-cache-main-

      - uses: actions/configure-pages@v5
        id: pages

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          TZ: Europe/London
        run: |
          hugo \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --minify \
            --gc \
            --logLevel debug \
            --templateMetrics \
            --templateMetricsHints \

      - name: Pull draft branch
        run: |
          git fetch origin draft
          git checkout draft

      - name: Extract draft branch name
        id: extract_draft_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Build draft with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_PUBLISHDIR: ./public/draft
          TZ: Europe/London
        run: |
          hugo \
            --baseURL "${{ steps.pages.outputs.base_url }}/draft/" \
            --minify \
            --gc \
            --logLevel debug \
            --templateMetrics \
            --templateMetricsHints \
            -- buildDrafts

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: ".git|.husky"
          path: ./
          depth: 5

      - uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.ARTEFACT_NAME }}
          path: ${{ env.HUGO_PUBLISHDIR }}

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/draft') && github.event_name == 'push'
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: ${{ env.ARTEFACT_NAME }}
